---
- name: Deploy Simple Nginx App on OpenShift
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Apply Nginx Deployment, Service, and Route
      ansible.builtin.command: |
        oc apply -f - <<EOF_APP
        apiVersion: apps.openshift.io/v1
        kind: DeploymentConfig
        metadata:
          name: simple-nginx-app
          namespace: aap # CONFIRMED ROSA PROJECT NAME
        spec:
          replicas: 1
          selector:
            app: simple-nginx-app
          template:
            metadata:
              labels:
                app: simple-nginx-app
            spec:
              containers:
                - name: nginx
                  image: nginx:latest
                  ports:
                    - containerPort: 80
                  imagePullPolicy: IfNotPresent
          triggers:
            - type: ConfigChange
            - type: ImageChange
              imageChangeParams:
                automatic: true
                containerNames:
                  - nginx
                from:
                  kind: ImageStreamTag
                  name: nginx:latest
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: simple-nginx-svc
          namespace: aap # CONFIRMED ROSA PROJECT NAME
        spec:
          selector:
            app: simple-nginx-app
          ports:
            - protocol: TCP
              port: 80
              targetPort: 80
        ---
        apiVersion: route.openshift.io/v1
        kind: Route
        metadata:
          name: simple-nginx-route
          namespace: aap # CONFIRMED ROSA PROJECT NAME
        spec:
          to:
            kind: Service
            name: nginx-svc
          port:
            targetPort: 80-tcp
          tls:
            termination: edge
            insecureEdgeTerminationPolicy: Redirect
        EOF_APP
      args:
        stdin: yes
      changed_when: true
      delegate_to: localhost
      run_once: true
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}" # Pass kubeconfig from credential
