- name: Deploy Simple Apache HTTPD App on OpenShift
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - kubernetes.core

  tasks:

    - name: Create Apache HTTPD Deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: simple-apache-app # New name for deployment
            namespace: aap # CONFIRMED ROSA PROJECT NAME
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: simple-apache-app
            template:
              metadata:
                labels:
                  app: simple-apache-app
              spec:
                containers:
                  - name: apache
                    image: httpd:latest # Using Apache HTTPD image
                    ports:
                      - containerPort: 80 # Default Apache port
                    imagePullPolicy: IfNotPresent
                securityContext: # Keep security context for general compatibility
                  runAsUser: 1000
                  fsGroup: 1000
                  allowPrivilegeEscalation: false

    - name: Expose Apache HTTPD via a Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: simple-apache-svc # New name for service
            namespace: aap # CONFIRMED ROSA PROJECT NAME
          spec:
            selector:
              app: simple-apache-app # Matches new app label
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80

    - name: Create Route to expose Apache HTTPD
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: simple-apache-route # New name for route
            namespace: aap # CONFIRMED ROSA PROJECT NAME
          spec:
            to:
              kind: Service
              name: simple-apache-svc # Matches new service name
            port:
              targetPort: 80
