---
- name: Deploy Simple Nginx App on OpenShift (Using Existing ConfigMap)
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Apply Nginx DeploymentConfig, Service, and Route
      kubernetes.core.k8s:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        state: present
        definition:
          - apiVersion: apps.openshift.io/v1
            kind: DeploymentConfig
            metadata:
              name: simple-nginx-app
              namespace: aap # CONFIRMED ROSA PROJECT NAME
            spec:
              replicas: 1
              selector:
                app: simple-nginx-app
              template:
                metadata:
                  labels:
                    app: simple-nginx-app
                spec:
                  volumes: # ADDED Volume to mount ConfigMap
                    - name: nginx-config-volume
                      configMap:
                        name: nginx-config # REFERENCING MANUALLY CREATED CONFIGMAP
                  containers:
                    - name: nginx
                      image: nginxinc/nginx-unprivileged:latest
                      ports:
                        - containerPort: 8080
                      imagePullPolicy: IfNotPresent
                      securityContext:
                        runAsNonRoot: true
                      volumeMounts: # ADDED Volume Mount
                        - name: nginx-config-volume
                          mountPath: /etc/nginx/nginx.conf
                          subPath: nginx.conf # Mount as a file, not a directory
              triggers:
                - type: ConfigChange
          - apiVersion: v1
            kind: Service
            metadata:
              name: simple-nginx-svc
              namespace: aap # CONFIRMED ROSA PROJECT NAME
            spec:
              selector:
                app: simple-nginx-app
              ports:
                - protocol: TCP
                  port: 8080
                  targetPort: 8080
          - apiVersion: route.openshift.io/v1
            kind: Route
            metadata:
              name: simple-nginx-route
              namespace: aap # CONFIRMED ROSA PROJECT NAME
            spec:
              to:
                kind: Service
                name: simple-nginx-svc
              port:
                targetPort: 8080-tcp
              tls:
                termination: edge
                insecureEdgeTerminationPolicy: Redirect
