---
- name: Deploy Nginx application on OpenShift (via oc commands)
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Ensure oc CLI is available (pre-check)
      ansible.builtin.command: oc version --client
      changed_when: false
      delegate_to: localhost
      run_once: true

    - name: Create Nginx DeploymentConfig
      ansible.builtin.command: |
        oc apply -f - <<EOF_DC
        apiVersion: apps.openshift.io/v1
        kind: DeploymentConfig
        metadata:
          name: nginx-app
          namespace: aap # CONFIRMED ROSA PROJECT NAME
        spec:
          replicas: 1
          selector:
            app: nginx-app
          template:
            metadata:
              labels:
                app: nginx-app
            spec:
              containers:
                - name: nginx
                  image: nginx:latest
                  ports:
                    - containerPort: 80
                  imagePullPolicy: IfNotPresent
          triggers:
            - type: ConfigChange
            - type: ImageChange
              imageChangeParams:
                automatic: true
                containerNames:
                  - nginx
                from:
                  kind: ImageStreamTag
                  name: nginx:latest
        EOF_DC
      args:
        stdin: yes # This tells command module to read from stdin
      changed_when: true
      delegate_to: localhost
      run_once: true
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}" # Pass kubeconfig from credential

    - name: Create Nginx Service
      ansible.builtin.command: |
        oc apply -f - <<EOF_SVC
        apiVersion: v1
        kind: Service
        metadata:
          name: nginx-svc
          namespace: aap # CONFIRMED ROSA PROJECT NAME
        spec:
          selector:
            app: nginx-app
          ports:
            - protocol: TCP
              port: 80
              targetPort: 80
        EOF_SVC
      args:
        stdin: yes
      changed_when: true
      delegate_to: localhost
      run_once: true
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"

    - name: Create Nginx Route
      ansible.builtin.command: |
        oc apply -f - <<EOF_ROUTE
        apiVersion: route.openshift.io/v1
        kind: Route
        metadata:
          name: nginx-route
          namespace: aap # CONFIRMED ROSA PROJECT NAME
        spec:
          to:
            kind: Service
            name: nginx-svc
          port:
            targetPort: 80-tcp
          tls:
            termination: edge
            insecureEdgeTerminationPolicy: Redirect
        EOF_ROUTE
      args:
        stdin: yes
      changed_when: true
      delegate_to: localhost
      run_once: true
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
