- name: Deploy NGINX Hello World App on OpenShift
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - kubernetes.core

  tasks:

    - name: Create a ConfigMap with index.html
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: nginx-html
            namespace: default # CONFIRMED ROSA PROJECT NAME
          data:
            index.html: |
              <html>
              <head><title>Hello</title></head>
              <body>
                <h1>Hello from Ansible default on OpenShift!</h1>
              </body>
              </html>

    - name: Create NGINX Deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            namespace: default # CONFIRMED ROSA PROJECT NAME
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                # --- START OF MODIFIED SECTION ---
                # Removed initContainers block entirely
                securityContext: # Added security context for permissions
                  runAsUser: 1000 # Common non-root user ID
                  fsGroup: 1000   # Common group ID for volume permissions
                  allowPrivilegeEscalation: false # Good practice
                containers:
                  - name: nginx
                    image: nginx:latest
                    ports:
                      - containerPort: 80
                    volumeMounts:
                      - name: html
                        mountPath: /usr/share/nginx/html
                      - name: nginx-cache-volume # Mount the cache volume
                        mountPath: /var/cache/nginx
                    # Add securityContext directly to the container if needed, but usually pod-level is enough
                    # securityContext:
                    #   runAsNonRoot: true
                    #   readOnlyRootFilesystem: true # Nginx needs to write to cache, so this might conflict
                volumes:
                  - name: html
                    configMap:
                      name: nginx-html
                  - name: nginx-cache-volume # Define the emptyDir volume for cache
                    emptyDir: {}
                # --- END OF MODIFIED SECTION ---

    - name: Expose NGINX via a Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-service
            namespace: default # CONFIRMED ROSA PROJECT NAME
          spec:
            selector:
              app: nginx
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80

    - name: Create Route to expose NGINX (OpenShift specific)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: nginx-route
            namespace: default # CONFIRMED ROSA PROJECT NAME
          spec:
            to:
              kind: Service
              name: nginx-service
            port:
              targetPort: 80
