- name: Deploy Plain Nginx App on OpenShift (Volume Cache)
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - kubernetes.core

  tasks:

    - name: Create NGINX Deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: plain-nginx-deployment # New name for deployment
            namespace: default # CONFIRMED ROSA PROJECT NAME
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: plain-nginx
            template:
              metadata:
                labels:
                  app: plain-nginx
              spec:
                securityContext:
                  runAsUser: 1000
                  fsGroup: 1000
                  allowPrivilegeEscalation: false
                containers:
                  - name: nginx
                    image: nginx:latest
                    ports:
                      - containerPort: 80
                    # --- START OF MODIFIED SECTION ---
                    volumeMounts: # Add volume mount for cache
                      - name: nginx-cache-volume
                        mountPath: /var/cache/nginx
                volumes: # Define the emptyDir volume for cache
                  - name: nginx-cache-volume
                    emptyDir: {}
                # --- END OF MODIFIED SECTION ---

    - name: Expose NGINX via a Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: plain-nginx-service # New name for service
            namespace: default # CONFIRMED ROSA PROJECT NAME
          spec:
            selector:
              app: plain-nginx
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80

    - name: Create Route to expose NGINX (OpenShift specific)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: plain-nginx-route # New name for route
            namespace: default # CONFIRMED ROSA PROJECT NAME
          spec:
            to:
              kind: Service
              name: plain-nginx-service
            port:
              targetPort: 80
