- name: Deploy Final Apache HTTPD App on OpenShift
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - kubernetes.core

  tasks:

    - name: Create Apache HTTPD Deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: final-apache-app # NEW DEPLOYMENT NAME
            namespace: aap # CONFIRMED ROSA PROJECT NAME
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: final-apache-app
            template:
              metadata:
                labels:
                  app: final-apache-app
              spec:
                containers:
                  - name: apache
                    image: httpd:latest # Using Apache HTTPD image
                    ports:
                      - containerPort: 80
                    imagePullPolicy: Always # Ensure fresh pull
                securityContext:
                  runAsUser: 1000
                  fsGroup: 1000
                  allowPrivilegeEscalation: false

    - name: Expose Apache HTTPD via a Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: final-apache-svc # NEW SERVICE NAME
            namespace: aap # CONFIRMED ROSA PROJECT NAME
          spec:
            selector:
              app: final-apache-app # Matches new app label
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80

    - name: Create Route to expose Apache HTTPD
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: final-apache-route # NEW ROUTE NAME
            namespace: aap # CONFIRMED ROSA PROJECT NAME
          spec:
            to:
              kind: Service
              name: final-apache-svc # Matches new service name
            port:
              targetPort: 80
