- name: Deploy Simple Nginx App on OpenShift (SCC & Port Compliant)
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Apply Nginx Deployment, Service, and Route
      kubernetes.core.k8s:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        state: present
        definition:
          - apiVersion: apps.openshift.io/v1
            kind: DeploymentConfig
            metadata:
              name: simple-nginx-app
              namespace: aap # CONFIRMED ROSA PROJECT NAME
            spec:
              replicas: 1
              selector:
                app: simple-nginx-app
              template:
                metadata:
                  labels:
                    app: simple-nginx-app
                spec:
                  containers:
                    - name: nginx
                      image: nginxinc/nginx-unprivileged:latest # Image runs on non-privileged port
                      ports:
                        - containerPort: 8080 # Port changed to 8080
                      imagePullPolicy: IfNotPresent
                      securityContext: # Security Context for non-root
                        runAsNonRoot: true
              triggers: # MODIFIED: Only ConfigChange trigger remains
                - type: ConfigChange # Keep this trigger
                # REMOVED: - type: ImageChange block that caused the error
          - apiVersion: v1
            kind: Service
            metadata:
              name: simple-nginx-svc
              namespace: aap # CONFIRMED ROSA PROJECT NAME
            spec:
              selector:
                app: simple-nginx-app
              ports:
                - protocol: TCP
                  port: 8080 # Service port changed to 8080
                  targetPort: 8080 # Target port changed to 8080
          - apiVersion: route.openshift.io/v1
            kind: Route
            metadata:
              name: simple-nginx-route
              namespace: aap # CONFIRMED ROSA PROJECT NAME
            spec:
              to:
                kind: Service
                name: simple-nginx-svc
              port:
                targetPort: 8080-tcp # Route target port changed to 8080-tcp
              tls:
                termination: edge
                insecureEdgeTerminationPolicy: Redirect
