---
- name: Deploy Simple Nginx App on OpenShift
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create Nginx DeploymentConfig
      ansible.builtin.command: |
        oc apply -f - <<EOF_DC
        apiVersion: apps.openshift.io/v1
        kind: DeploymentConfig
        metadata:
          name: simple-nginx-app
          namespace: aap # CONFIRMED ROSA PROJECT NAME
        spec:
          replicas: 1
          selector:
            app: simple-nginx-app
          template:
            metadata:
              labels:
                app: simple-nginx-app
            spec:
              containers:
                - name: nginx
                  image: nginx:latest
                  ports:
                    - containerPort: 80
                  imagePullPolicy: IfNotPresent
              triggers:
                - type: ConfigChange
                - type: ImageChange
                  imageChangeParams:
                    automatic: true
                    containerNames:
                      - nginx
                    from:
                      kind: ImageStreamTag
                      name: nginx:latest
        EOF_DC
      args:
        stdin: yes
      changed_when: true
      delegate_to: localhost
      run_once: true
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"

    - name: Create Nginx Service
      ansible.builtin.command: |
        oc apply -f - <<EOF_SVC
        apiVersion: v1
        kind: Service
        metadata:
          name: simple-nginx-svc
          namespace: aap # CONFIRMED ROSA PROJECT NAME
        spec:
          selector:
            app: simple-nginx-app
          ports:
            - protocol: TCP
              port: 80
              targetPort: 80
        EOF_SVC
      args:
        stdin: yes
      changed_when: true
      delegate_to: localhost
      run_once: true
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"

    - name: Create Nginx Route
      ansible.builtin.command: |
        oc apply -f - <<EOF_ROUTE
        apiVersion: route.openshift.io/v1
        kind: Route
        metadata:
          name: simple-nginx-route
          namespace: aap # CONFIRMED ROSA PROJECT NAME
        spec:
          to:
            kind: Service
            name: simple-nginx-svc
          port:
            targetPort: 80-tcp
          tls:
            termination: edge
            insecureEdgeTerminationPolicy: Redirect
        EOF_ROUTE
      args:
        stdin: yes
      changed_when: true
      delegate_to: localhost
      run_once: true
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
