- name: Deploy Plain Nginx App on OpenShift (No Custom HTML)
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - kubernetes.core

  tasks:

    # Removed the 'Create a ConfigMap with index.html' task

    - name: Create NGINX Deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: plain-nginx-deployment # New name for deployment
            namespace: default # CONFIRMED ROSA PROJECT NAME
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: plain-nginx
            template:
              metadata:
                labels:
                  app: plain-nginx # New app label
              spec:
                securityContext:
                  runAsUser: 1000
                  fsGroup: 1000
                  allowPrivilegeEscalation: false
                containers:
                  - name: nginx
                    image: nginx:latest # Reverting to standard nginx:latest for simplicity
                    ports:
                      - containerPort: 80
                    # Removed volumeMounts for html and cache
                # Removed 'volumes' section entirely

    - name: Expose NGINX via a Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: plain-nginx-service # New name for service
            namespace: default # CONFIRMED ROSA PROJECT NAME
          spec:
            selector:
              app: plain-nginx # Matches new app label
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80

    - name: Create Route to expose NGINX (OpenShift specific)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: plain-nginx-route # New name for route
            namespace: default # CONFIRMED ROSA PROJECT NAME
          spec:
            to:
              kind: Service
              name: plain-nginx-service # Matches new service name
            port:
              targetPort: 80
